### ISSUE TITLE
NullReferenceException when using AddAzureStorage with DefaultAzureCredential in Aspire.Hosting.Azure.Storage 9.5.2

### ISSUE THREAD

**Issue by kaby10** [microsoft/aspire#12519]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When calling AddAzureStorage("name") in an AppHost project, the application throws a System.NullReferenceException originating from Azure.Identity.dll. This occurs during credential initialization when using a custom credential switch that falls back to DefaultAzureCredential. It seems that AddAzureStorage attempts to resolve TokenCredential even when the storage is expected to run using the Azurite emulator, likely because no explicit connection string or emulator configuration is provided.

### Expected Behavior

When running the AppHost with AddAzureStorage("name") and no explicit cloud credentials, the application should initialize the storage resource successfully without attempting to resolve TokenCredential or throwing any exceptions.

### Steps To Reproduce

```
var builder = DistributedApplication.CreateBuilder(args);

var storageDi = builder
    .AddAzureStorage("name")
    .RunAsEmulator(x =>
    {
        x.WithImageTag("latest");
    });

builder.Build().Run();
```

### Exceptions (if any)

System.NullReferenceException: 'Object reference not set to an instance of an object.'

Object reference not set to an instance of an object. at Azure.Identity.DefaultAzureCredentialFactory.TryCreateDevelopmentBrokerOptions(InteractiveBrowserCredentialOptions& options)

<img width="1002" height="252" alt="Image" src="https://github.com/user-attachments/assets/0a85ce3d-680c-4c62-9bdb-b9123c853481" />

### .NET Version info

.NET SDK:
 Version:           9.0.306
 Commit:            cc9947ca66
 Workload version:  9.0.300-manifests.abe91478
 MSBuild version:   17.14.28+09c1be848

### Anything else?

<PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
<PackageReference Include="Aspire.Hosting.Azure.Storage" Version="9.5.2" />

**Comment by davidfowl** [comment]
It's a "first chance exception" (exceptions that are caught) and everything should still work just fine. It's fixed in the later version of Azure.Identity. 

PS: Usually debugger settings do not break on these types of exceptions.

**Comment by timheuer** [comment]
@kaby10 In your Visual Studio debugger settings (Debug...Options) do you have "Enable Just My Code" **unchecked**?

**Comment by kaby10** [comment]
First of all, thank you both for your responses! I really appreciate the help and the time you took to look into this.

@timheuer Yes, I had “Enable Just My Code” checked, but unchecking it didn’t solve the issue.
@davidfowl Updating to the latest version solved the problem. Thanks

**Comment by radical** [comment]
This was incorrectly closed by https://github.com/dotnet/aspire/pull/12845 . Re-opening.

**Comment by Jordan-Murray** [comment]
@timheuer Enabling 'Just my code' worked for me, thanks!

**Comment by maddymontaquila** [comment]
This has been implemented in #12845. Closing as resolved. Thank you for the proposal! If you have follow-up feature requests, please open a new issue.

**Comment by davidfowl** [comment]
Reopening after reviewing the recent bulk closure. The close comment appears to cite work that does not fully address this issue, so this should remain open for normal triage.
